VITE_SUPABASE_URL=https://nkljmavbtabuohjyguwn.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbGptYXZidGFidW9oanlndXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzYzNDYsImV4cCI6MjA2ODgxMjM0Nn0.J7DW0qa49DsyFCpvxou_ZOiM9yH-DUXfdxqB5MWloRk
/// <reference types="vite/client" />
